### ISSUE TITLE
League System

### ISSUE THREAD

**Issue by a9977321** [Babygogogo/TinyWarsClient#111]
We are planning to implement a league system in tinywars for map & CO testing purpose. Feel free to share your opinion on what the League system should be like.

**Comment by a9977321** [comment]
Translation of my proposal will be found at the end of this message. 

图1
![图1](https://user-images.githubusercontent.com/25498933/85676395-2578b100-b6f9-11ea-9b56-633667a123d0.png)

在multiplayer菜单里有1个“新的联赛”，点击后会出现个如图1所示的界面，界面也可以做成批准回看界面那样（如图2）。
图2
![图2](https://user-images.githubusercontent.com/25498933/85676501-3c1f0800-b6f9-11ea-8220-8f2c3e4998c3.png)

玩家可以选择愿意匹配的联赛，这些选项会影响游戏规则（当前只影响CO的ban list，未来可以加入快局，随机CO，雾战等等）。Classic包含了除t0 Caulder, t1 Isabella以外的原版CO；All CO包含了所有的CO，All CO（t0 excluded）包含了除t0以外的所有CO。玩家可以选择多个类型，但至少需要选择1种，默认全部选择。


图3
![图3](https://user-images.githubusercontent.com/25498933/85676532-44774300-b6f9-11ea-839c-0aac2da55855.png)

玩家点击cancel以后可以回到multiplayer界面；选择至少一个类型后点击confirm，会弹出一个警告框，表明之后无法撤消建局，并提供确认/取消选项（如图3）。再次确认以后会出现以下2情况中的1种：
（1）玩家会进入一个游戏创建页面，地图由系统指定，CO禁用符合玩家所选择的标准之一，玩家始终是先手，玩家只可以选择CO，然后点击“确认”建立游戏（如图4）。这个界面没有取消按钮，如果玩家在这个界面中下线，那么系统会用预先选好的默认CO作为该玩家的CO直接建立游戏。
图4
![图4](https://user-images.githubusercontent.com/25498933/85676579-50fb9b80-b6f9-11ea-9b70-088e6a03b29c.png)

（2）玩家会进入一个加入游戏界面，这个游戏的CO禁用符合玩家所选择的标准之一，玩家始终是后手（先手已经被占用）玩家无法看到对手玩家的信息和CO选择，玩家只可以选择CO，然后点击“确认”开始游戏（如图5）。与（1）中相同玩家无法取消加入游戏的步骤，下线处理方法同上。
图5
![图5](https://user-images.githubusercontent.com/25498933/85676591-535df580-b6f9-11ea-948c-cb4c0a163600.png)


建局玩家可以在“退出房间”中找到还没开的局，虽然他们无法退出这个游戏；已经开始的对局会出现在“继续战斗”之中。

附注：
一个对局长时间没有被加系统会优先让下一个玩该模式的玩家加入该对局,其他情况下玩家是建局还是加局、加入哪个对局都是随机的；
玩家最后确认建局/加局时可以增加一个确认框，与目前游戏一致（如图3）；
系统从图池中随机筛选地图，在有数据后可以增加地图出现的权重以保证数据的充分；
在得到初步数据后可以增加分级；
可以考虑禁用局内聊天系统，并且隐藏对手用户名，并禁止观战

**Comment by a9977321** [comment]
Translation for the previous post: 
Babygogogo listed his proposal for reference. 

Features: 

- Players creating the game can ban COs before they know the exact map for the game. 

- Players joining the game can decide who will be first

Steps: 
1. Create/Join a game
2. Prepare for the game
3. Start the game

Step1: Create/join a game
In the game there will be a button called "Create/Join Leage game". After clicking the button the system will determine whether there are exisiting games matching the ranking of the player. 
If there are suitable games the player will join the game and enter step2. The player cannot exit the game. 
If there are no suitable games available, the player will enter the Create Game page. (Players having too many games to be joined will return to main menu after receiving a message) The player got 2 options then. 
1) Cancel--The player gives up creating the game by doing so. 
2) The player may set the CO ban list and whether the FOW is on if he didn't want to cancel the game. (NOTE: the map is unknown when he makes the setting) The game is created after the setting is complete. When other players press the Create/join League game button they will join the game if the ranking is appropriate and enter step2. 

Step2:  Preparation before the game
There will be a "preparation" menu in the game, where players can find their games in preparation there. Choosing a game there will lead players to the preparation page of a game, where the following info will be showed, but unable to be revised: 

- Map & Rules (Maps will be selected randomly from a map pool based on whether it's FOW game or not, the timer will be set to 3 days)

- The ban list of CO (determined by player creating the game)

- Fow or not  (determined by player creating the game)

At the same time the following info is available and can be revised: 

- The CO you're going to use

- Your turn order (available for player joining the game)
This page will not display the CO, player nickname and turn order. 

When both players choose their COs the game will begin. If the setting is not done in 3 days, it will be decided randomly and the game will begin.

**Comment by Babygogogo** [comment]
另一套可供参考的流程设计。

# 流程主要特点
1. 规则本身对各参战玩家绝对公平。
2. 无法ban选co。
3. 将逐步引入争议较小的custom co进入可选co池。

# 流程步骤构成
1. 建立/加入房间
2. 战前准备
3. 正式开打

正式开打无需多言，以下开始详细描述前两个阶段。

## 步骤1：建立/加入房间
游戏内提供一个建立/加入房间二合一的按钮。玩家点击后，系统弹窗让玩家选择打明战或雾战，玩家选定后，系统立刻判定当前存在的房间中，有没有与玩家积分相匹配的房间。

- 存在可以直接匹配的房间
  
  玩家直接自动进入该房间且无法再退出，此房间直接进入步骤2。

- 不存在可以直接匹配的房间

  如果此时玩家创建了的房间数量超出限制，则给出相应提示，并取消建立房间。否则，系统将直接建好房间。当其他玩家点击建立/加入房间按钮时，若系统自动匹配加入此房间，则此房间进入步骤2。

## 步骤2：战前准备
游戏内提供一个战前准备的按钮。玩家点击后，会列出玩家所参与的、处于此步骤的所有房间。选择任意一个房间会显示战前准备页面，此页面会展示以下信息，这些信息不可修改：

- 地图及其规则设定（地图由系统根据是否雾战，自动从图池中随机选择；boot模式全部规定为标准3天）
- 是否雾战
- 双方先后手（由系统随机决定）

同时，此页面提供以下可选项：
- 自己使用哪个co

此页面不会向各方展示玩家名称、使用哪个co的信息。

当对战各方均选好了co后，游戏即正式开打。如果一个房间进入步骤2后，三天内各方仍未进行上述设定，则由系统自动随机选上并正式开打。

**Comment by zhaotiantong** [comment]
由zhaotiantong预先对每张图设定几种分级
当有玩家质疑某张图的某个co分级不合理时，由zhaotiantong研究后进行调整


zhaotiantong方案一：
玩家只选择是否雾战，是否有自定义co，总共2*2=4种选择
如果没有相同选择的其他玩家，则该玩家等待匹配
如果有相同选择的其他玩家，则两名玩家立即进入系统指定地图指定分级的房间，不可退出


zhaotiantong方案二：
系统开8个天梯对战房间
玩家可以看到：房间的地图，是否雾战，能够使用哪些co，是否已经有玩家加入
玩家可以自己选择进入哪个房间
房间如果没有满员，则玩家看不到先后手，不能选co，但可以随时退出
房间如果满员，则玩家不能再退出，同时分配双方先后手，开始选co。并且该房间不再对外显示，系统生成一个新的天梯对战房间
生成房间后一周内没有满员，则自动替换为新的房间

**Comment by a9977321** [comment]
Translation for previous 2 posts

Pending

**Comment by a9977321** [comment]
方案2: 增加2个额外按钮, 联赛匹配和联赛偏好。在联赛偏好中有联赛图池中所有地图，玩家可以设置每个地图每个模式想用什么co

按匹配键后可以选择想要参加的模式，然后开始匹配。如果没有符合要求的对局玩家会作为p1自动建局，如果有符合要求的对局玩家会自动加入，待加入的对局可以在离开对局中找到，开始的对局在继续战斗中可以找到

**Comment by a9977321** [comment]
After discussion babygogogo's 2nd plan will be adopted, where both players can ban 3 COs, while in the original version the ban list is determined by the player himself. The issue will be closed when the system is online.
