### ISSUE TITLE
Add preset rules for single play mode

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#117]
Currently, single play map could only use custom map settings, which is bad for ` War room` and `campaign room.`
for the map editor, just add options on the rule-setting panel to sure whatever mode the rules apply for is ok. 
![image](https://user-images.githubusercontent.com/20500319/90009013-e0700480-dccf-11ea-92dc-a9e2a9ce7313.png)

**Comment by Babygogogo** [comment]
Added in the test version.
