### ISSUE TITLE
Incomplete translation when entering private games

### ISSUE THREAD

**Issue by a9977321** [Babygogogo/TinyWarsClient#119]
The password notification, the buttons as well as the instructions need proper translation. (6 places in total)
The details as well as the suggested translation are listed in the enclosed pic. 
![Incomplete_translation_1](https://user-images.githubusercontent.com/25498933/90622344-8e872b80-e247-11ea-9d28-d0ed2cadb5f1.png)

**Comment by RushFTK** [comment]
the title using new string `A0131`
`密码` in join game panel replaced as `私人房间`, using new string `B406`
while others use current settings.
