### ISSUE TITLE
Action menu appear in a demo

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#12]
### Bug Detail
You can open action menu on demo, like you playing this game. (but can not actually doing action).
![bug_screenshot](https://user-images.githubusercontent.com/20500319/65309781-5d2d5800-dbbf-11e9-84bd-ff7e7ec83a50.jpg)

### Reproduce Step
1. Select a demo to view.  
2. Stop in some rounds current player have unit havent move yet.  
3. Double click curennt player's unmoved unit, you will see action menu like you play this game.  

### Reason Analyze  (Optional)
Analyzing...  

### Soluation (Optional)
Analyzing...

**Comment by Babygogogo** [comment]
Actually this is a dedicated design. With this design, players can check the movement and damages for units in battle. This may help players to understand the game.
