### ISSUE TITLE
Zone should be hidden durning power if unrelated with specially ability

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#20]
## Descripition  
Suggest that hidden CO Zone display effect durning COP/SCOP ***unless*** this CO have zone relatived skills such as `Unit in zone gain +10/+10 durning COP ` or `CO can still charge durning COP/SCOP` .   

Previously CO Zone are disappear by default because none of CO have such ability in DoR and the Zone is hidden by default; in current version, consider ability mentioned above, CO Zone will **never** disapper, like screenshot shows below:  
![9C37DE6PH`S6FRI$YJSZCA](https://user-images.githubusercontent.com/20500319/67834042-4b759380-fb21-11e9-9574-e8aae2d1b0c8.png)
Zone should be hidden during COP/SCOP if uncessary. because it may let player troubled if his CO D2D ability is still existed. also, if some CO's zone hidden during power while somes are not, player will more easily noticed that he / his enemy actived power, and this power have zone related skills.

**Comment by Babygogogo** [comment]
Fixed. Thanks for the report.

**Comment by RushFTK** [comment]
![8U%9)S2AI9E2_S~D%$YE1~V](https://user-images.githubusercontent.com/20500319/68172053-177ef000-ffb1-11e9-9e70-2db08b2d0961.jpg)
Currently solution cause some no D2D ability CO (like `Mira`)'s COZ disappeared.

**Comment by RushFTK** [comment]
`Mira`'s Zone have been successfully visiable.
