### ISSUE TITLE
Map Selecteion select a incorrect zoom spann island in default.

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#22]
![0KW1GKJJTO C6SDF8255DNV](https://user-images.githubusercontent.com/20500319/67912139-e757db80-fbc3-11e9-962f-460b848b6274.png)
A player will see max zommed Spann island on the first time he enter into map selected page.

**Comment by a9977321** [comment]
It is still the case in create game menu, but it is not always Spann Island
