### ISSUE TITLE
Incomplete translation on `game settings` interface.

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#29]
this interface appear in multiple menus
![image](https://user-images.githubusercontent.com/20500319/68187551-ecf95b00-ffe1-11e9-82c6-fd606f07b8ec.png)
![image](https://user-images.githubusercontent.com/20500319/68187570-f71b5980-ffe1-11e9-9572-18147b34ef05.png)
![image](https://user-images.githubusercontent.com/20500319/68187961-07800400-ffe3-11e9-86d7-6d07c66cf812.png)
The `Create Game` menu (3rd screenshot) had provieded some translation of words. to solve this issue, simpliy keep them consist.

**Comment by RushFTK** [comment]
for contributor who didnt know how to fix this glitch, can see [**this issue**](https://github.com/Babygogogo/TinyWarsClient/issues/28) for referance.

**Comment by a9977321** [comment]
最多20字，可留空=20 words for maximum, optional
最多4位数字，可留空=4 digits for maximum, optional
最多50字，可留空=50 words for maximum, optional

**Comment by a9977321** [comment]
Chinese name tags in 'Join game' & 'Game preview' have been translated in 'Create game' menu in most cases. 
保留房间=Cancel; 退出房间=Exit Game

**Comment by RushFTK** [comment]
some have been fixed from above update (screenshot 1,screenshot 3), some still happen.
