### ISSUE TITLE
Gage's Battleship have incorrect extra damage.

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#33]
![image](https://user-images.githubusercontent.com/20500319/68365074-a4b97480-016a-11ea-9372-762d22dab9ba.png)
![image](https://user-images.githubusercontent.com/20500319/68365079-a84cfb80-016a-11ea-9e07-d013092bcc58.png)
Tested in Origional DOR, the gage COU ship's attack buffed 50% damage (Ace + 20% + 10% COZ All + 20% COZ Special skills)
but in TW it buffed extra 20% damage (since he is both navy and indirect unit).

**Comment by Babygogogo** [comment]
emmm 这个bug并不存在，gage的技能是专用的，加成没有问题
