### ISSUE TITLE
平衡性更新 ：Lee 的加强

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#34]
> 【活跃】Purifier Warmech  14:17:08
@Babygogogo lee已更新，d2d加了10攻防，power加了10防

此贴可以继续探讨Lee是否被加强和加强的细节。

**Comment by a9977321** [comment]
2019/11/7 Lee will receive +10/+10 buff for all units in COZ to improve his game performance. In previous game play it is clear that Lee's units in coz cannot deal with opponents' units in COZ effectively thanks to the +10 defense bonus shared by almost all other COs (exception: Mira, Mauser and Alexender) Replays for reference: icy vs V. Airfortress, Hawk vs Lee, Black Patch War

**Comment by RushFTK** [comment]
Lee have been updated on above update
