### ISSUE TITLE
Incomplete translation on `terrain info` interface

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#38]
![image](https://user-images.githubusercontent.com/20500319/68543507-dd6b7f00-03f2-11ea-9cf0-113122879562.png)
1. Some terrain can use some abbreviation instead of full name, below you can find abbreviation origional DoR used.
![image](https://user-images.githubusercontent.com/20500319/68543526-1c99d000-03f3-11ea-8374-46c18d937119.png)
2. incomplete translate.

**Comment by a9977321** [comment]
defense boost; Income; Vision; Units can hide; Defeat when captured; Repair; Prodction facility; Stat boost

MP cost

**Comment by a9977321** [comment]
The translation issue has been fixed

**Comment by Babygogogo** [comment]
It seems that this issue has been fixed.
