### ISSUE TITLE
用户是否应允许自设定伤害预期的工作模式(讨论)

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#39]
- 雾战可设定推测的敌方拥有塔数

现在TW中，雾战伤害预览的工作模式为：看到对方有多少塔，伤害预估为多少。目的是不暴露对手拥有的塔数，但会造成大多数情况下，伤害预览的效果失真。
考虑到玩家可以推测出对方拥有的塔数，是否应该建立一个高级选项，令用户可以设定推测对方拥有的塔数以校准伤害预览？
此外，除了可以设定数值，是否有必要增加以下选项？
- `自动` ： 和现有方式一样，看到多少塔算对方有多少加成。
- `反射` ： 和现有方式相反，看不到的塔都视作对手已拥有的。

- 基于运气的伤害计算

伤害预览是否需要显示运气范围值？称其为“完整”模式，现今的伤害预览称为"简单"模式。
现在的模式下(简单模式)，显示2行：
`攻：{A}/{C}`
`反：{D2}/{E}`
完整模式下显示三行：
`攻：[{A},{B}]/{C}`
`反O：[{D1},{E1}]/{F}`
`反I：[{D2},{E2}]/{F}`
其中:
- `{A}`：不带运气的伤害值（或者最小运气的伤害值？不清楚现行的体系）
- `{B}`：带**最大**运气的伤害值
- `{C}`：敌单位剩余血量
- `{D}`:  不带运气反击的伤害值，其中1以A计算反击单位剩余血量，2以B计算反击单位剩余血量。
- `{E}`:  带最大运气反击的伤害值，其中1以A计算反击单位剩余血量，2以B计算反击单位剩余血量。
- `{F}`:  我方单位的血量

**Comment by a9977321** [comment]
I suggest rather than full customization of the expected damage, a damage calculator should be made available on the top tool bar.

**Comment by RushFTK** [comment]
*"伤害计算器"*会不会在操作上带来更多的不便？毕竟本身手机就很难点按钮了

**Comment by a9977321** [comment]
To be specific, I'd like to have a button at the top right corner, which leads to a new page with a damage calculator

**Comment by a9977321** [comment]
https://github.com/a9977321/tinywars_dmgcalculator_20191121/releases

Damage Calculators for PC players. Possible uses include damage simulation and FOW damage calculation.
