### ISSUE TITLE
terrain is static 

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#4]
Compared with babywars, the terrain image changed in a static way for effective reason.  
For game experience, it's a option, to find a way, use animated terrain again.

**Comment by Babygogogo** [comment]
动画机制其实已经做了，只是因为会导致卡顿所以屏蔽了，后续考虑增加游戏选项让玩家决定是否开启

**Comment by Babygogogo** [comment]
The tile animations are added already.
