### ISSUE TITLE
T0 update?

### ISSUE THREAD

**Issue by a9977321** [Babygogogo/TinyWarsClient#41]
For now there are only 2 COs in tier 0, one of which is underpowered (Grat t0, compared with Caulder t0). We plan to add more COs into tier 0 to make it tier suitable for competition. 

In this update we will add/revise the following: 

t0 Tabitha coz=0, coz metre: 10/35/70; power metre --/70; d2d: All units in COZ +100/+100; scop: All units +100/+100; A 3-radius missile will be launced at area with most enemy HP/value, dealing 8HP damage to units within

t0 Grat's starting coz will be expanded to 4 (from 2)

**Comment by RushFTK** [comment]
this balance updated have been online on above update.
![image](https://user-images.githubusercontent.com/20500319/68987276-5a6b7e00-0863-11ea-99fa-4ab943d0485a.png)
![image](https://user-images.githubusercontent.com/20500319/68987280-62c3b900-0863-11ea-9fe3-682aced9dd28.png)

**Comment by a9977321** [comment]
Suggestions regarding balance updates about t0 COs can be listed here. For instance V. Airfortress suggested buffing t0 Tabitha further with another 20/20 buff. That means Tabitha t0 should give all units in COZ 220/220 stats. More tests are required before formal requests.
