### ISSUE TITLE
Incomplete translation on `change nickname\change discord id` interface

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#44]
![image](https://user-images.githubusercontent.com/20500319/69024566-3db77d80-09fe-11ea-89e5-361cbbfb685e.png)
![image](https://user-images.githubusercontent.com/20500319/69024574-490aa900-09fe-11ea-871e-8e28f7a1e861.png)

@a9977321 giving correct translate text.

**Comment by a9977321** [comment]
Change Nickname/ New Nickname/ Confirm
Note: You can use any character for the nickname, and the nickname should consist of at least 4 characters. 

Change Discord ID
New ID
By entering your correct discord ID and joining the following discord server (the link can be copied) you can receive tinywars-related information, including turn notification.
