### ISSUE TITLE
In-game chat

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#71]
like what [Babygogogo/Babywars](https://github.com/Babygogogo/BabyWars) did. a in-game chat system is necessary for player who didnt want use 3rd-party community software (such as Discord, QQ, etc,), to communite with other players.  

plus, we need `friends` system and a notification for friends online.

**Comment by a9977321** [comment]
An messagebox like awbw is usually suffice, but a chatroom is even better.

**Comment by a9977321** [comment]
#110
