### ISSUE TITLE
showing "TODO!!" when clicking "detail" on building panel at Replay modes

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#75]
![image](https://user-images.githubusercontent.com/20500319/69899159-6e53cb80-139d-11ea-9f57-54f70efc94f5.png)

**Comment by a9977321** [comment]
(Imo the better solution to this is to disable the 'details' button here. )

**Comment by RushFTK** [comment]
i just want copy codes from `McwProduceUnitPanel.ts` to keep them functionable consist. 
(btw i will begin to fix these bugs after finished working `ReplayConsolePanel`)
