### ISSUE TITLE
User should back to panel he visit after close `profile` panel.

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#77]
Currently back to `main menu` in default.

**Comment by a9977321** [comment]
Current setting is somehow clearer compared with the opposite. A not-so-good alternative is to limit your access to the profile panel.

**Comment by RushFTK** [comment]
in my opinion, if top-bar can be visiable in all `war menu` panels, it shouldn't be panels-related. (so i decided to desinged like *"back to panel when you click"* )
if a button disappeared suddenly, that will cause player confused.
