### ISSUE TITLE
Player's Setting not sync with view

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#93]
![2020-02-02_14-38-55](https://user-images.githubusercontent.com/20500319/73604336-1ff3c080-45ca-11ea-9edd-38619796c1d2.gif)
for example, when you click left for the first time,**it seemed** nothing changed, the settings change after click again.
in fact, the setting have already changed. that means, if you click `>>` on Force twice, you will see your force is `2(Blue)` but your force is `3(Yellow)`

**Comment by Babygogogo** [comment]
Fixed.
