### ISSUE TITLE
Player's setting disappaeared on first load

### ISSUE THREAD

**Issue by RushFTK** [Babygogogo/TinyWarsClient#94]
![image](https://user-images.githubusercontent.com/20500319/73604366-aa3c2480-45ca-11ea-9578-7d00efcc346c.png)
after you create a free battle for the first time, the player's setting will disappear.
![3A@$3DLBRPR7S6WKT6AE(JY](https://user-images.githubusercontent.com/20500319/73604401-1880e700-45cb-11ea-9f13-c756f06fa47c.png)
the next free battle's players setting will show the previous map's players setting.
change any settings will sync the player's setting.
it likes delay problem on #93 .

**Comment by Babygogogo** [comment]
Fixed.
